name: BukkitGateWayEndPortal
version: 1.0
main: me.jonnyfant.bukkitgatewayendportal.BukkitGateWayEndPortal
api-version: 1.18
commands:
  transformendgateway:
    usage: /<command> [distance]
    permission: op